spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: letmein
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        security: DEBUG
application:
  security:
    jwt:
      secret-key: 0RreVLYdwmtbHj5wP8gkjUrqxPznlQtA4SECIXqPFLbRvSBUniXPkybxuN5E211